const earlyProjects = [
  {
    id: 1,
    title: 'Image System for Social Platform',
    imageUrl: '/assets/motion-visual/02800_pz1.png',
    microCaption: 'UX design and frontend architecture for a large-scale image-sharing system, exploring non-linear navigation across high-volume user-generated content.',
    fullCaption: 'Reimagined collective image browsing beyond traditional grid layouts. Designed UX architecture, managed beta contributors, and prototyped interaction patterns for navigating large volumes of mobile-generated images. Focused on scalable information structure and user-driven discovery models.',
    tileSize: 'large',
    category: 'startup',
    order: 1,
  },
  {
    id: 2,
    title: 'Alpine Navigation Microsite',
    imageUrl: '/assets/motion-visual/01800_alpine.png',
    microCaption: 'UX and interactive system design for a performance-optimized product manual microsite.',
    fullCaption: 'Designed and developed a structured microsite for the Alpine NVE-N872A navigation tool. Implemented lightweight vector assets and structured text imports to ensure fast load times, maintainability, and efficient content updates while delivering an engaging product experience.',
    tileSize: 'large',
    category: 'motion',
    order: 2,
  },
  {
    id: 4,
    title: 'Interactive Learning Simulation',
    imageUrl: '/assets/motion-visual/13800_spaces.png',
    microCaption: 'Led design and full application development of a real-time 3D educational simulation integrating motion capture and physics systems.',
    fullCaption: 'Architected and developed a real-time simulation enabling children to explore forces and friction within a physical play space. Integrated live motion capture streams into a 3D physics environment with scenario saving, multi-camera views, and server synchronization. Responsible for UX, animation systems, and custom class architecture integrating 3D and physics libraries.',
    tileSize: 'xlarge',
    category: 'motion',
    order: 4,
  },
  {
    id: 3,
    title: 'Prime Event Group Animated Website',
    imageUrl: '/assets/motion-visual/16800_prime.png',
    microCaption: 'Interactive site optimized for progressive image loading and structured content management.',
    fullCaption: 'Developed an image-heavy interactive site using progressive loading strategies to maintain responsiveness. Structured text content via XML to allow non-technical content updates without modifying application code. Balanced visual richness with performance efficiency.',
    tileSize: 'large',
    category: 'motion',
    order: 3,
  },
  {
    id: 6,
    title: 'SparkHill Animated Site',
    imageUrl: '/assets/motion-visual/05800_sparkhill.png',
    microCaption: 'User-driven animation system supporting dynamic state changes across responsive layouts.',
    fullCaption: 'Designed and developed an interactive environment featuring dynamic graphic systems responsive to user navigation. Implemented animation logic capable of mid-path redirection, enabling seamless transitions across multiple screen states while preserving performance and visual continuity.',
    tileSize: 'large',
    category: 'motion',
    order: 6,
  },
  {
    id: 7,
    title: 'Nokia Theater Opening',
    imageUrl: '/assets/motion-visual/06800_nokia.png',
    microCaption: 'High-performance interactive site using minimal assets and dynamic animation systems.',
    fullCaption: 'Engineered an interactive experience using minimal image assets to animate large-scale color and light transitions efficiently. Structured text via XML for flexible client updates while maintaining performance and visual fidelity.',
    tileSize: 'large',
    category: 'motion',
    order: 7,
  },
  {
    id:5,
    title: 'Timothy Britten Parker Site',
    imageUrl: '/assets/motion-visual/04800_tbparker.png',
    microCaption: 'UX and structured content design for a multi-disciplinary artist platform supporting media playback and discoverability.',
    fullCaption: 'Designed and developed a structured web presence clarifying cross-disciplinary work across acting and music. Implemented organized content architecture, media playback integration, and search-optimized structure to support discoverability and usability.',
    tileSize: 'medium',
    category: 'highlight',
    order:5,
  },
  {
    id: 8,
    title: 'ButterVine',
    imageUrl: '/assets/motion-visual/03800_buttervine.png',
    microCaption: 'Branding and UX architecture for a product-focused e-commerce site.',
    fullCaption: 'Developed a visual brand system and frontend experience supporting product discovery and close-view inspection. Designed interaction patterns to enhance storytelling while maintaining search visibility and structured content organization.',
    tileSize: 'medium',
    category: 'highlight',
    order: 8,
  },
  {
    id: 9,
    title: 'Hide & Seek DVD Site',
    imageUrl: '/assets/motion-visual/10800_hideseek.png',
    microCaption: 'Interactive promotional site aligning motion design with marketing objectives.',
    fullCaption: 'Designed and developed a promotional website translating cinematic tone into interactive web motion. Structured the experience to support marketing goals while delivering an immersive yet performant user journey.',
    tileSize: 'medium',
    category: 'Motion',
    order: 9,
  },
  {
    id: 10,
    title: "Children's Album Cover",
    imageUrl: '/assets/motion-visual/11800_bent.png',
    microCaption: "Visual identity and packaging design for a children's music release.",
    fullCaption: "Designed compact disk and packaging visuals aligning playful energy with brand credibility for parents. Focused on clarity of messaging, target audience alignment, and cohesive visual system development.",
    tileSize: 'medium',
    category: 'highlight',
    order: 10,
  },
  {
    id: 11,
    title: 'Lotus Banner Campaign',
    imageUrl: '/assets/motion-visual/17800_lotus.png',
    microCaption: 'Mathematically driven animation system for high-performance banner campaign.',
    fullCaption: 'Developed animated banners using mathematical curve calculations to simulate dynamic tire motion. Optimized for file size constraints while maintaining precision, realism, and visual impact.',
    tileSize: 'medium',
    category: 'highlight',
    order: 11,
  },
  {
    id: 12,
    title: 'Barclays iShares Newschool',
    imageUrl: '/assets/motion-visual/07800_nsishere.png',
    microCaption: 'Multi-format animated banner campaign optimized for performance and consistency.',
    fullCaption: 'Produced multi-size banner campaigns, adapting animation systems to maintain visual consistency across formats while meeting strict file size and performance constraints.',
    tileSize: 'small',
    category: 'highlight',
    order: 12,
  },
  {
    id: 13,
    title: 'Barclays iShares Morningstar',
    imageUrl: '/assets/motion-visual/08800_ishares.png',
    microCaption: 'Multi-format animated banner campaign optimized for performance and consistency.',
    fullCaption: 'Produced multi-size banner campaigns, adapting animation systems to maintain visual consistency across formats while meeting strict file size and performance constraints.',
    tileSize: 'small',
    category: 'highlight',
    order: 13,
  },
  {
    id: 14,
    title: 'Barclays iShares Newschool',
    imageUrl: '/assets/motion-visual/15800_nsmove4.png',
    microCaption: 'Multi-format animated banner campaign optimized for performance and consistency.',
    fullCaption: 'Produced multi-size banner campaigns, adapting animation systems to maintain visual consistency across formats while meeting strict file size and performance constraints.',
    tileSize: 'small',
    category: 'highlight',
    order: 14,
  },
  {
    id: 15,
    title: 'Image-Sharing Startup Research',
    imageUrl: '/assets/motion-visual/12800_pz2.png',
    microCaption: 'User-centered research informing interaction design for a social image-sharing platform.',
    fullCaption: 'Conducted immersive user sessions with amateur photographers to study behavioral patterns and content creation habits. Insights informed refinements to navigation and interaction design, improving usability for non-professional contributors.',
    tileSize: 'large',
    category: 'startup',
    order: 15,
  },
  {
    id: 16,
    title: 'Pinger Product Animation',
    imageUrl: '/assets/motion-visual/14800_pinger.png',
    microCaption: 'Product animation designed for clarity, pacing, and brand alignment.',
    fullCaption: "Created a product explainer animation translating feature functionality into clear visual narrative. Focused on timing, information hierarchy, and brand consistency for social platform distribution.",
    tileSize: 'small',
    category: 'highlight',
    order: 16,
  },
];

const visualStyleImages = [
  {
    id: 1,
    imageURL: '/assets/style/style_0010126.jpg',
    order: 1,
  },
  {
    id: 2,
    imageURL: '/assets/style/style_0020126.jpg',
    order: 2,
  },
  {
    id: 3,
    imageURL: '/assets/style/style_0030126.jpg',
    order: 3,
  },
  {
    id: 4,
    imageURL: '/assets/style/style_0040126.jpg',
    order: 4,
  },
  {
    id: 5,
    imageURL: '/assets/style/style_0050126.jpg',
    order: 5,
  },
  {
    id: 6,
    imageURL: '/assets/style/style_0060126.jpg',
    order: 6,
  },
  {
    id: 7,
    imageURL: '/assets/style/style_0070126.jpg',
    order: 7,
  },
  {
    id: 8,
    imageURL: '/assets/style/style_0080126.jpg',
    order: 8,
  },
  {
    id: 9,
    imageURL: '/assets/style/style_0090126.jpg',
    order: 9,
  },
  {
    id: 10,
    imageURL: '/assets/style/style_0100126.jpg',
    order: 10,
  },
  {
    id: 11,
    imageURL: '/assets/style/style_0110126.jpg',
    order: 11,
  },
  {
    id: 12,
    imageURL: '/assets/style/style_0120126.jpg',
    order: 12,
  },
  {
    id: 13,
    imageURL: '/assets/style/style_0130126.jpg',
    order: 13,
  },
  {
    id: 14,
    imageURL: '/assets/style/style_0140126.jpg',
    order: 14,
  },
  {
    id: 15,
    imageURL: '/assets/style/style_0150126.jpg',
    order: 15,
  },
  {
    id: 16,
    imageURL: '/assets/style/style_0160126.jpg',
    order: 16,
  },
  {
    id: 17,
    imageURL: '/assets/style/style_0170126.jpg',
    order: 17,
  },
  {
    id: 18,
    imageURL: '/assets/style/style_0180126.jpg',
    order: 18,
  },
  {
    id: 19,
    imageURL: '/assets/style/style_0190126.jpg',
    order: 19,
  },
  {
    id: 20,
    imageURL: '/assets/style/style_0200126.jpg',
    order: 20,
  },
  {
    id: 21,
    imageURL: '/assets/style/style_0210126.jpg',
    order: 21,
  },
  {
    id: 22,
    imageURL: '/assets/style/style_0220126.jpg',
    order: 22,
  },
  {
    id: 23,
    imageURL: '/assets/style/style_0230126.jpg',
    order: 23,
  },
  {
    id: 24,
    imageURL: '/assets/style/style_0240126.jpg',
    order: 24,
  },
  {
    id: 25,
    imageURL: '/assets/style/style_0250126.jpg',
    order: 25,
  },
  {
    id: 26,
    imageURL: '/assets/style/style_0260126.jpg',
    order: 26,
  },
  {
    id: 27,
    imageURL: '/assets/style/style_0270126.jpg',
    order: 27,
  },
  {
    id: 28,
    imageURL: '/assets/style/style_0280126.jpg',
    order: 28,
  },
  {
    id: 29,
    imageURL: '/assets/style/style_0290126.jpg',
    order: 29,
  },
  {
    id: 30,
    imageURL: '/assets/style/style_0300126.jpg',
    order: 30,
  },
  {
    id: 31,
    imageURL: '/assets/style/style_0310126.jpg',
    order: 31,
  },
  {
    id: 32,
    imageURL: '/assets/style/style_0320126.jpg',
    order: 32,
  },
  {
    id: 33,
    imageURL: '/assets/style/style_0330126.jpg',
    order: 33,
  },
  {
    id: 34,
    imageURL: '/assets/style/style_0340126.jpg',
    order: 34,
  },
  {
    id: 35,
    imageURL: '/assets/style/style_0350126.jpg',
    order: 35,
  },
  {
    id: 36,
    imageURL: '/assets/style/style_0360126.jpg',
    order: 36,
  },
  {
    id: 37,
    imageURL: '/assets/style/style_0370126.jpg',
    order: 37,
  },
  {
    id: 38,
    imageURL: '/assets/style/style_0380126.jpg',
    order: 38,
  },
  {
    id: 39,
    imageURL: '/assets/style/style_0390126.jpg',
    order: 39,
  },
  {
    id: 40,
    imageURL: '/assets/style/style_0400126.jpg',
    order: 40,
  },
  {
    id: 41,
    imageURL: '/assets/style/style_0410126.jpg',
    order: 41,
  },
  {
    id: 42,
    imageURL: '/assets/style/style_0420126.jpg',
    order: 42,
  },
  {
    id: 43,
    imageURL: '/assets/style/style_0430126.jpg',
    order: 43,
  },
  {
    id: 44,
    imageURL: '/assets/style/style_0440126.jpg',
    order: 44,
  },
  {
    id: 45,
    imageURL: '/assets/style/style_0450126.jpg',
    order: 45,
  },
  {
    id: 46,
    imageURL: '/assets/style/style_0460126.jpg',
    order: 46,
  },
  {
    id: 47,
    imageURL: '/assets/style/style_0470126.jpg',
    order: 47,
  },
  {
    id: 48,
    imageURL: '/assets/style/style_0480126.jpg',
    order: 48,
  },
  {
    id: 49,
    imageURL: '/assets/style/style_0490126.jpg',
    order: 49,
  },
  {
    id: 50,
    imageURL: '/assets/style/style_0500126.jpg',
    order: 50,
  },
  {
    id: 51,
    imageURL: '/assets/style/style_0510126.jpg',
    order: 51,
  },
  {
    id: 52,
    imageURL: '/assets/style/style_0520126.jpg',
    order: 52,
  },
  {
    id: 53,
    imageURL: '/assets/style/style_0530126.jpg',
    order: 53,
  },
  {
    id: 54,
    imageURL: '/assets/style/style_0540126.jpg',
    order: 54,
  },
  {
    id: 55,
    imageURL: '/assets/style/style_0550126.jpg',
    order: 55,
  },
  {
    id: 56,
    imageURL: '/assets/style/style_0560126.jpg',
    order: 56,
  },
  {
    id: 57,
    imageURL: '/assets/style/style_0570126.jpg',
    order: 57,
  },
  {
    id: 58,
    imageURL: '/assets/style/style_0580126.jpg',
    order: 58,
  },
  {
    id: 59,
    imageURL: '/assets/style/style_0590126.jpg',
    order: 59,
  },
  {
    id: 60,
    imageURL: '/assets/style/style_0600126.jpg',
    order: 60,
  },
  {
    id: 61,
    imageURL: '/assets/style/style_0610126.jpg',
    order: 61,
  },
  {
    id: 62,
    imageURL: '/assets/style/style_0620126.jpg',
    order: 62,
  },
  {
    id: 63,
    imageURL: '/assets/style/style_0630126.jpg',
    order: 63,
  },
  {
    id: 64,
    imageURL: '/assets/style/style_0640126.jpg',
    order: 64,
  },
  {
    id: 65,
    imageURL: '/assets/style/style_0650126.jpg',
    order: 65,
  },
  {
    id: 66,
    imageURL: '/assets/style/style_0660126.jpg',
    order: 66,
  },
  {
    id: 67,
    imageURL: '/assets/style/style_0670126.jpg',
    order: 67,
  },
  {
    id: 68,
    imageURL: '/assets/style/style_0680126.jpg',
    order: 68,
  },
  {
    id: 69,
    imageURL: '/assets/style/style_0690126.jpg',
    order: 69,
  },
  {
    id: 70,
    imageURL: '/assets/style/style_0700126.jpg',
    order: 70,
  },
  {
    id: 71,
    imageURL: '/assets/style/style_0710126.jpg',
    order: 71,
  },
  {
    id: 72,
    imageURL: '/assets/style/style_0720126.jpg',
    order: 72,
  },
  {
    id: 73,
    imageURL: '/assets/style/style_0730126.jpg',
    order: 73,
  },
  {
    id: 74,
    imageURL: '/assets/style/style_0740126.jpg',
    order: 74,
  },
  {
    id: 75,
    imageURL: '/assets/style/style_0750126.jpg',
    order: 75,
  },
  {
    id: 76,
    imageURL: '/assets/style/style_0760126.jpg',
    order: 76,
  },
  {
    id: 77,
    imageURL: '/assets/style/style_0770126.jpg',
    order: 77,
  },
  {
    id: 78,
    imageURL: '/assets/style/style_0780126.jpg',
    order: 78,
  },
  {
    id: 79,
    imageURL: '/assets/style/style_0790126.jpg',
    order: 79,
  },
  {
    id: 80,
    imageURL: '/assets/style/style_0800126.jpg',
    order: 80,
  },
  {
    id: 81,
    imageURL: '/assets/style/style_0810126.jpg',
    order: 81,
  },
  {
    id: 82,
    imageURL: '/assets/style/style_0820126.jpg',
    order: 82,
  },
  {
    id: 83,
    imageURL: '/assets/style/style_0830126.jpg',
    order: 83,
  },
  {
    id: 84,
    imageURL: '/assets/style/style_0840126.jpg',
    order: 84,
  },
  {
    id: 85,
    imageURL: '/assets/style/style_0850126.jpg',
    order: 85,
  },
  {
    id: 86,
    imageURL: '/assets/style/style_0860126.jpg',
    order: 86,
  },
  {
    id: 87,
    imageURL: '/assets/style/style_0870126.jpg',
    order: 87,
  },
  {
    id: 88,
    imageURL: '/assets/style/style_0880126.jpg',
    order: 88,
  },
  {
    id: 89,
    imageURL: '/assets/style/style_0890126.jpg',
    order: 89,
  },
  {
    id: 90,
    imageURL: '/assets/style/style_0900126.jpg',
    order: 90,
  },
  {
    id: 91,
    imageURL: '/assets/style/style_0910126.jpg',
    order: 91,
  },
  {
    id: 92,
    imageURL: '/assets/style/style_0920126.jpg',
    order: 92,
  },
  {
    id: 93,
    imageURL: '/assets/style/style_0930126.jpg',
    order: 93,
  },
  {
    id: 94,
    imageURL: '/assets/style/style_0940126.jpg',
    order: 94,
  },
  {
    id: 95,
    imageURL: '/assets/style/style_0950126.jpg',
    order: 95,
  },
  {
    id: 96,
    imageURL: '/assets/style/style_0960126.jpg',
    order: 96,
  },
  {
    id: 97,
    imageURL: '/assets/style/style_0970126.jpg',
    order: 97,
  },
  {
    id: 98,
    imageURL: '/assets/style/style_0980126.jpg',
    order: 98,
  },
  {
    id: 99,
    imageURL: '/assets/style/style_0990126.jpg',
    order: 99,
  },
  {
    id: 100,
    imageURL: '/assets/style/style_1000126.jpg',
    order: 100,
  },
  {
    id: 101,
    imageURL: '/assets/style/style_1010126.jpg',
    order: 101,
  },
  {
    id: 102,
    imageURL: '/assets/style/style_1020126.jpg',
    order: 102,
  },
  {
    id: 103,
    imageURL: '/assets/style/style_1030126.jpg',
    order: 103,
  },
  {
    id: 104,
    imageURL: '/assets/style/style_1040126.jpg',
    order: 104,
  },
  {
    id: 105,
    imageURL: '/assets/style/style_1050126.jpg',
    order: 105,
  },
  {
    id: 106,
    imageURL: '/assets/style/style_1060126.jpg',
    order: 106,
  },
  {
    id: 107,
    imageURL: '/assets/style/style_1070126.jpg',
    order: 107,
  },
  {
    id: 108,
    imageURL: '/assets/style/style_1080126.jpg',
    order: 108,
  },
  {
    id: 109,
    imageURL: '/assets/style/style_1090126.jpg',
    order: 109,
  },
  {
    id: 110,
    imageURL: '/assets/style/style_1100126.jpg',
    order: 110,
  },
  {
    id: 111,
    imageURL: '/assets/style/style_1110126.jpg',
    order: 111,
  },
];